### ISSUE TITLE
求解，始终报错，不知道什么问题

### ISSUE THREAD

**Issue by kzaopa-0x99** [f0ng/autoDecoder#1]
![image](https://user-images.githubusercontent.com/82259855/160551514-3b9c7af7-7011-4192-a48c-908b83872110.png)

**Comment by f0ng** [comment]
看样子是获取jar路径出错了，师傅加下我微信吧，f-f0ng

**Comment by f0ng** [comment]
问题在于写`properties`文件的时候没有判断系统，新版本`0.11`修复该问题
