### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by peiqiF4ck** [f0ng/autoDecoder#10]
有的app是请求不加密但是返回使用的aes加密。这种只能用autodecoder的接口来编写。但是如果可以加入但自带的解密解密接口来说会比较方便希望作者可以将这个功能加入进去。另外如果作者能在自带加密解密中携带更多的加密算法比rsa等。还有aes常用的模式会更加方便的工具很不错。

**Comment by f0ng** [comment]
针对`有的app是请求不加密但是返回使用的aes加密。这种只能用autodecoder的接口来编写`这个，如果响应包是纯文本，是可以做到返回加密，请求不加密的；如果不是纯文本的，是只能autoDecoder去实现了
rsa这种算法在加入的考虑当中，未来可能会加入

**Comment by peiqiF4ck** [comment]
我后来使用brida解决这个问题了。都是好工具但autodecoder确实强悍。那我的那个app是请求没有加密但是用autodecoder自带加密来说。不用接口你只要勾选以后。他自动给你进行加密处理。应该在搞一个明文出现xxx时候不加密返回有加密的时候。自动解密这种。插件是有文明请求出现.xxx就行加密。请求密文出现xxx不加密。并没有类似 请求中明文出现xxx不加密的方式。对于返回来说一般肯定都加密。主要是请求。最后希望软件越来越强

**Comment by f0ng** [comment]
你说的蛮好的，不过就`我的那个app是请求没有加密`来说，你可以把请求包的加密方式置为null，即请求包中没有任何加密；
针对于响应包的解密，后续会加入正则去实现
