### ISSUE TITLE
使用过程中发现Turbo Intruder 不生效

### ISSUE THREAD

**Issue by baimasi** [f0ng/autoDecoder#11]
Turbo Intruder 不生效，未做其他插件的测试，
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/28396944/233796255-bcaa2ac8-c816-403e-962b-c8438ca61b72.png">
目前没有做其他插件的测试，是因为turbo Intruder 有什么特殊的地方吗，来logger也没有看到请求。
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/28396944/233796311-9e4714b4-70bc-4d73-a0d8-37f34f5bd6c5.png">

**Comment by f0ng** [comment]
如果turbo Intruder发出的请求Tool模块是Extender是会生效的，从图里面看，好像并没有

**Comment by f0ng** [comment]
经测试，extender是可以生效的，如图，为配合log4j被扫进行的extender加密测试

**Comment by f0ng** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/48286013/233947048-82debfc4-d969-441c-a1f0-9f0fa6ab101e.png">
<img width="831" alt="image" src="https://user-images.githubusercontent.com/48286013/233947095-8f42266c-beff-4e6f-bb42-c008d8752b5f.png">
