### ISSUE TITLE
intruder模块自动加密未生效

### ISSUE THREAD

**Issue by Hus3ar** [f0ng/autoDecoder#13]
配置好后，在repeater模块请求和响应包解密都没有问题，然后配置好了正则
![image](https://github.com/f0ng/autoDecoder/assets/38522348/347d58c0-43bf-401e-b4cc-8d1e83f45099)
但是在intruder模块，爆破明文时，没有自动加密
![image](https://github.com/f0ng/autoDecoder/assets/38522348/b46b4ee1-261a-4bed-aaa8-f99c615a8ea0)

**Comment by f0ng** [comment]
测试是可以的，你输入明文关键字了吗
<img width="1130" alt="image" src="https://github.com/f0ng/autoDecoder/assets/48286013/9586430f-aa5f-49b3-83c2-1129f4f1bc5b">

**Comment by Hus3ar** [comment]
可以了，我的操作问题
