### ISSUE TITLE
嗯,小号又骂人了,围观一下

### ISSUE THREAD

**Issue by xupeichen** [f0ng/autoDecoder#19]
> > 有这个闲工夫劝你多搞搞技术，自己被踢了怨不得别人，四十多岁人了，搞这些花里胡哨的 <img alt="image" width="929" src="https://user-images.githubusercontent.com/48286013/260197514-966e58ac-d9b4-4450-91cb-19b821fd8a76.png">
> > <img alt="image" width="363" src="https://user-images.githubusercontent.com/48286013/260197527-ce82a204-e757-43b3-9555-22f47e3df97a.png">
> 
> 1. 徐培宸,善待用你工具的每个人,你闲工夫多也没见你多说一句给你的爱好者
> 2. 短信是让你来看GitHub,你以为不能做其他事吗

够胆查不够胆发？别装那个大逼斗了，小心把自己反噬了，问问题别人给你办法你不用，你是一点脑子没有啊？反过来威胁谁呢，几把给你能的，那么能咋开个小号灰溜溜的来底下评论呢，人品败坏

_Originally posted by @n1ko61 in https://github.com/f0ng/autoDecoder/issues/18#issuecomment-1675857794_
         

徐培宸,这是你的小号?,你也不看看我的名字,小号是你相当就能当的?小学拼音白学了

**Comment by f0ng** [comment]
让我用小号骂你？不值，得看自己配不配

**Comment by jtsqrj** [comment]
没看懂,是不是这个作者csdn被黑了然后就用小号骂另一个人?
