### ISSUE TITLE
嗯,小号开始骂人了

### ISSUE THREAD

**Issue by xupeichen** [f0ng/autoDecoder#20]
就不惯着你，40来岁连人都做不明白，跳梁小丑除了急你还有点啥？恼羞成怒啦，你该反省的是你为什么能一边用着开源的东西一边骂原作者，且是别人已经给你解决的思路的前提下，你真没脑子啊，饭嘴边要喂你吃，你是他儿子？给你惯的，《甲方你王哥》？

_Originally posted by @n1ko61 in https://github.com/f0ng/autoDecoder/issues/18#issuecomment-1675860168_

 徐培宸你也就这点素质了,围观的看看,开源作者小号开始骂街了,这个帖子真是开对了,谁素质差不用我说了吧

**Comment by f0ng** [comment]
看看呗，看看你这个跳梁小丑怎么蹦跶的，你不会是火柴人分柴吧，王哥，被踢了，来我这出气，别想不开啊，别抑郁了

**Comment by jtsqrj** [comment]
我觉得楼上的回复间接承认了,这个帖子来来回回只有他们两个在吵架

**Comment by klmyssn** [comment]
坚定完毕，王哥就是火柴人中年人40岁加强版本，两个小号搞双簧辛苦你了王哥
