### ISSUE TITLE
大佬，这个插件支持请求的时候输入明文自动加密成密文发送吗？

### ISSUE THREAD

**Issue by lyx744** [f0ng/autoDecoder#23]
比如在repeater中，我直接输入明文，点击send的时候插件自动将明文加密后发送

**Comment by f0ng** [comment]
当然支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lyx744 ***@***.***&gt;
发送时间: 2023年9月30日 12:02
收件人: f0ng/autoDecoder ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [f0ng/autoDecoder] 大佬，这个插件支持请求的时候输入明文自动加密成密文发送吗？ (Issue #23)





 
比如在repeater中，我直接输入明文，点击send的时候插件自动将明文加密后发送
