### ISSUE TITLE
遇到了一个问题 不知道是bug还是啥

### ISSUE THREAD

**Issue by ruisika** [f0ng/autoDecoder#25]
我使用nodejs写了一个脚本来进行接口的加解密，在插件自带的接加密窗口可以正常加解密
![image](https://github.com/f0ng/autoDecoder/assets/87137234/e0120221-47b3-432a-9538-8443dea4c5e2)

但是到其他界面只能进行加密操作，如果点击autodecoder则没有将解密的结构进行返回到bp上。解密结果已经可以在我控制台打印出来并且执行了返回操作。
![image](https://github.com/f0ng/autoDecoder/assets/87137234/3762fad4-b336-4d6e-b3db-03d40303d149)
按理说不应该加解密窗口哪里的可以正常运行到其他界面也是可以的嘛。我排查了四五个小时找到问题出在哪里。

**Comment by f0ng** [comment]
可能是选项中开关没保存，问题还存在的话，师傅可以加一下我微信`f-f0ng`

**Comment by f0ng** [comment]
问题在于返回包格式问题(`\r\n\r\n\r\n\r\n`)，后续可能会修改该传输方式或者添加提示
