### ISSUE TITLE
pkcs7padding 自带算法解密好像不支持这个填充

### ISSUE THREAD

**Issue by qrekkwijjtx54** [f0ng/autoDecoder#29]
pkcs7padding 自带算法解密好像不支持这个填充，请问有解决办法吗？

**Comment by qrekkwijjtx54** [comment]
![image](https://github.com/user-attachments/assets/1a14bce1-0423-4990-b112-5afed63cb271)
最好可以自主选择位数.谢谢你的辛勤劳动的成果

**Comment by f0ng** [comment]
> pkcs7padding 自带算法解密好像不支持这个填充，请问有解决办法吗？

pkcs5模式即为pkcs7模式，可选秘钥长度暂时不增加，基本没有遇到
