### ISSUE TITLE
建议响应包也把头部字段返回来处理呢

### ISSUE THREAD

**Issue by gie-gie-gayhub** [f0ng/autoDecoder#3]
大大佬，建议添加请求头中有关键字的时候触发脚本处理以及响应包也把头部字段返回来处理的功能呢，有时候会用的到😅

**Comment by f0ng** [comment]
感谢师傅反馈，将在下个版本更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月10日(周二) 中午11:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [f0ng/autoDecoder] 建议响应包也把头部字段返回来处理呢 (Issue #3)




 
大大佬，建议添加请求头中有关键字的时候触发脚本处理以及响应包也把头部字段返回来处理的功能呢，有时候会用的到😅
