### ISSUE TITLE
最后一个空行被处理掉了

### ISSUE THREAD

**Issue by bmsh1t** [f0ng/autoDecoder#30]
最后一个空行默认被处理掉了，换不换行加密结果是一样的

**Comment by f0ng** [comment]
默认是处理掉的




------------------ 原始邮件 ------------------
发件人: bmsh1t ***@***.***&gt;
发送时间: 2024年8月16日 15:09
收件人: f0ng/autoDecoder ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [f0ng/autoDecoder] 最后一个空行被处理掉了 (Issue #30)
