### ISSUE TITLE
功能建议：与captcha-killer-modified的联动需求

### ISSUE THREAD

**Issue by K0uaz** [f0ng/autoDecoder#31]
遇到一个场景，首先会获取一个验证码，然后第二个请求包发送的时候是
{"isEncrypt":"Yes","nnerKey":"xxx","data":"ASE加密内容"}
其中data的内容是{"phone": "xxxx","immsgcode":"0159","type": ""}
通过调试找到了AES KEY，然后通过autodecoder的自带算法加解密在Repeater进行调试
但是每次请求完，验证码就会失效，因此想通过captcha-killer-modified配置ocr识别匹配到数字的验证码再放到immsgcode中
因此想通过@captcha@来配置自动获取验证码，但是发现两者无法联动，当发送如下的请求后
{"isEncrypt":"Yes","nnerKey":"xxx","data":"{"phone": "xxxx","immsgcode":"@captcha@","type": ""}"}
自动先AES加密了，没有再用@captcha@了

**Comment by f0ng** [comment]
复杂请求不推荐用自带，用接口即可，自带只适配较为单一场景


------------------ 原始邮件 ------------------
发件人: 絢辻詞 ***@***.***&gt;
发送时间: 2024年9月30日 21:50
收件人: f0ng/autoDecoder ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [f0ng/autoDecoder] 功能建议：与captcha-killer-modified的联动需求 (Issue #31)





 
遇到一个场景，首先会获取一个验证码，然后第二个请求包发送的时候是
 {"isEncrypt":"Yes","nnerKey":"xxx","data":"ASE加密内容"}
 其中data的内容是{"phone": "xxxx","immsgcode":"0159","type": ""}
 通过调试找到了AES KEY，然后通过autodecoder的自带算法加解密在Repeater进行调试
 但是每次请求完，验证码就会失效，因此想通过captcha-killer-modified配置ocr识别匹配到数字的验证码再放到immsgcode中
 在调试中发现，请求配置的明文{"isEncrypt":"Yes","nnerKey":"xxx","data":"{"phone": ***@***.***@","type": ""}"}

**Comment by K0uaz** [comment]
> 复杂请求不推荐用自带，用接口即可，自带只适配较为单一场景
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 絢辻詞 ***@***.***&gt; 发送时间: 2024年9月30日 21:50 收件人: f0ng/autoDecoder ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [f0ng/autoDecoder] 功能建议：与captcha-killer-modified的联动需求 (Issue #31) 遇到一个场景，首先会获取一个验证码，然后第二个请求包发送的时候是 {"isEncrypt":"Yes","nnerKey":"xxx","data":"ASE加密内容"} 其中data的内容是{"phone": "xxxx","immsgcode":"0159","type": ""} 通过调试找到了AES KEY，然后通过autodecoder的自带算法加解密在Repeater进行调试 但是每次请求完，验证码就会失效，因此想通过captcha-killer-modified配置ocr识别匹配到数字的验证码再放到immsgcode中 在调试中发现，请求配置的明文{"isEncrypt":"Yes","nnerKey":"xxx","data":"{"phone": ***@***.***@","type": ""}"} — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

哈哈，好的，也是。稍微费点时间
