### ISSUE TITLE
不走加密

### ISSUE THREAD

**Issue by zzhnohikari** [f0ng/autoDecoder#32]
大佬，这边进行了一个接口加解密脚本的编写，但是密文一直只走解密，转正明文之后修改明文不能走加密，
![image](https://github.com/user-attachments/assets/a1873d3e-c331-4971-9c09-59d1b7b4b6f9)
这个还会报错，提示接收到的headers为空，尝试了明文关键字和密文关键字也没效果，求助
![image](https://github.com/user-attachments/assets/5ff89079-2141-41da-8dca-d1e7441116fd)

**Comment by f0ng** [comment]
修改明文不走加密大概率是关键字问题；没有接收到headers可能是你保存配置出了问题

**Comment by zzhnohikari** [comment]
确实是这样，进交流群解决了，谢谢作者大大

**Comment by f0ng** [comment]
over
