### ISSUE TITLE
自带解密二次加密

### ISSUE THREAD

**Issue by tianq1ng** [f0ng/autoDecoder#35]
是我配置有问题吗，出现了二次AES加密，以下是我的配置
![image](https://github.com/user-attachments/assets/e70de7f0-a38e-42cf-9a06-6c5f5eb7a506)
![image](https://github.com/user-attachments/assets/0c4b3cbc-086d-4c53-a3a5-aaaf7160a0df)
在
Repeater的autodecode的时候发现logger经过了2二次AES加密，加密后的内容在进行AES加密，不是通过明文的方式加密
![image](https://github.com/user-attachments/assets/43daa335-c225-4eb1-966d-7753e63103af)
查看Logger日志
![image](https://github.com/user-attachments/assets/69de2ecb-acb1-4121-ae64-3ce20372de43)
![image](https://github.com/user-attachments/assets/161b2639-bed4-4c50-bdfb-5e3d5f0cc008)
发现Logger日志里面的值{"encryptedData":"nArXfVdnoe67UzojAPP2X+6qSiznLMBAI3a5Bi+zlNzLyT6Xnr7qdEiybRfWYC2S"} 进行了AES加密
![image](https://github.com/user-attachments/assets/5dd746bf-889b-42f2-8d7b-d52256613706)
{"encryptedData":"5BS7Zd/Co4b4b3zBG4/Xd1CjswAmh2EDZgMhZnJ2j/Qta0ax0BXThEE7rNCgIUTWsm9xeHF4R0Dorfx5nNB091LR5KC6wtIYaDgbQ0Q+JcE="}
![image](https://github.com/user-attachments/assets/d1791bd3-543f-4b84-837b-a27d7729387c)

**Comment by f0ng** [comment]
几点问题
1.高版本的bp不建议用扩展选项卡进行发包，参考https://github.com/f0ng/autoDecoder/blob/main/FAQ.md#0x10-%E6%98%8E%E6%96%87%E4%BF%AE%E6%94%B9%E5%90%8E%E8%BF%9B%E8%A1%8C%E5%8F%91%E5%8C%85%E4%BD%86%E6%98%AF%E8%AF%B7%E6%B1%82%E5%8C%85%E8%BF%94%E5%9B%9E%E5%8E%9F%E6%9D%A5%E7%9A%84%E6%98%8E%E6%96%87，这是你第一次加密的问题，因为发包实际上还是你的密文`Pretty`里的原数据包
2.关键字有问题，明文关键字设置的是`:`和`"`这就导致了密文也符合这个格式，所以会进行加密，这是你第二次加密的问题
