### ISSUE TITLE
开启插件后发包报错

### ISSUE THREAD

**Issue by Github3362** [f0ng/autoDecoder#36]
这是配置
![image](https://github.com/user-attachments/assets/db5179c7-f12b-4b00-8b38-7a235974f95c)
![image](https://github.com/user-attachments/assets/35614f33-8199-42ad-b0a3-d23667d32980)
没有开启插件情况下:
![image](https://github.com/user-attachments/assets/89d42a56-6ebb-4bef-b59b-f825f6e6820a)
开启情况下:(所又配置都保存过的)
![image](https://github.com/user-attachments/assets/803e0ce6-c5e1-4c4e-9442-79af596abec6)
![image](https://github.com/user-attachments/assets/a748e234-2858-4d0c-94ac-a12c413bdf82)

**Comment by Github3362** [comment]
我使用测试的是https://github.com/outlaws-bai/GalaxyDemo在一个靶场

**Comment by Github3362** [comment]
我测试使用的是这一个靶场
https://github.com/outlaws-bai/GalaxyDemo

**Comment by f0ng** [comment]
大概率请求包的加密错误，可以看下logger进行调试

**Comment by Github3362** [comment]
> 大概率请求包的加密错误，可以看下logger进行调试
dan's
java.lang.IllegalStateException: No match found
但是我的正则表达式没有问题啊,怎么会匹配不到
![image](https://github.com/user-attachments/assets/02add7da-8e58-4ed7-8f35-7050f205c253)

**Comment by f0ng** [comment]
"data":"(.*?)"
请参考案例的正则，不要自己写正则
https://github.com/f0ng/autoDecoder-usages/blob/main/%E8%87%AA%E5%B8%A6%E5%8A%A0%E8%A7%A3%E5%AF%86%E7%AE%97%E6%B3%95%E7%9A%84%E7%94%A8%E6%B3%95/%E6%8C%87%E5%AE%9A%E6%96%87%E6%9C%AC%E5%8A%A0%E5%AF%86/%E6%8C%87%E5%AE%9A%E6%96%87%E6%9C%AC%E5%8A%A0%E5%AF%86.md
