### ISSUE TITLE
没法修改参数

### ISSUE THREAD

**Issue by Matth3w001** [f0ng/autoDecoder#37]
<img width="1293" alt="image" src="https://github.com/user-attachments/assets/8528c054-ecfc-4af2-bb13-31666dd030b2">
我这里数据包加解密已经能看到了，但我修改请求包发包之后会直接变回原来的包发包

**Comment by f0ng** [comment]
参考https://github.com/f0ng/autoDecoder/blob/main/FAQ.md#0x10-%E6%98%8E%E6%96%87%E4%BF%AE%E6%94%B9%E5%90%8E%E8%BF%9B%E8%A1%8C%E5%8F%91%E5%8C%85%E4%BD%86%E6%98%AF%E8%AF%B7%E6%B1%82%E5%8C%85%E8%BF%94%E5%9B%9E%E5%8E%9F%E6%9D%A5%E7%9A%84%E6%98%8E%E6%96%87
