### ISSUE TITLE
自带接口对接报错问题

### ISSUE THREAD

**Issue by zyl973657019** [f0ng/autoDecoder#40]
直接请求是正常的，对接上去就报错了，求解答
![image](https://github.com/user-attachments/assets/11858aea-ad34-449f-8fd2-aab4c16df25c)
![image](https://github.com/user-attachments/assets/8e792b0c-27ae-41cd-a418-a765f1219cc1)

**Comment by f0ng** [comment]
你这个选项卡都没有，当然不生效，参考用法



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zyl973657019 ***@***.***&gt;
发送时间: 2024年12月28日 03:31
收件人: f0ng/autoDecoder ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [f0ng/autoDecoder] 自带接口对接报错问题 (Issue #40)





 
直接请求是正常的，对接上去就报错了，求解答
 image.png (view on web)
 image.png (view on web)
