### ISSUE TITLE
用例子试了一下，返回包提示解密错误

### ISSUE THREAD

**Issue by apt-kristaps** [f0ng/autoDecoder#5]
![image](https://user-images.githubusercontent.com/86959650/168640865-15ab0f12-6bdc-491a-8b51-213e50069c9b.png)

**Comment by f0ng** [comment]
麻烦师傅加下微信，f-f0ng

**Comment by f0ng** [comment]
应该是响应包选中了`autoDecoder`扩展选项卡，导致再次解密了，已经修复该显示bug了，还没更新，感谢师傅反馈

**Comment by apt-kristaps** [comment]
> autoDecoder

好的，谢谢  期待下次更新

**Comment by f0ng** [comment]
问题在于php的编码问题，例子中的响应包应为`Content-Length: 24`的，但是师傅的是`27`。经过证明，发现是php的编码问题
![image](https://user-images.githubusercontent.com/48286013/168757672-6351fba7-4b3b-4fc2-a806-89f84d102003.png)

**Comment by apt-kristaps** [comment]
> 以php的编码问题为例，问题中的响应包为应有的问题`Content-Length: 24`，但师傅是`27`。验证证明，发现是php的编码问题 ![图片](https://user-images.githubusercontent.com/48286013/168757672-6351fba7-4b3b-4fc2-a806-89f84d102003.png)

感谢大佬指点

**Comment by f0ng** [comment]
后续反馈：
将burp改成如下字体，乱码问题解决，burp字体显示问题，非php的原因
<img width="705" alt="image" src="https://user-images.githubusercontent.com/48286013/169190399-3c3c82b5-8f95-46bd-bbb6-1dd8b4bd8cbc.png">
