### ISSUE TITLE
师傅用的是什么版本的bp？

### ISSUE THREAD

**Issue by ketchup1995** [f0ng/autoDecoder#6]
如图，我可以解密，但是好像界面有点奇怪，而且repeater那里没有出现改插件的功能
![图片](https://user-images.githubusercontent.com/87350553/190092117-18832dee-24c2-42a2-9d8c-b20b0c5b900a.png)

**Comment by f0ng** [comment]
burp 2021.5.1

**Comment by f0ng** [comment]
没有出现改插件的功能因为没设置域名

**Comment by f0ng** [comment]
https://github.com/f0ng/autoDecoder/blob/main/FAQ.md#0x01%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BD%BF%E7%94%A8
参考
