### ISSUE TITLE
请问body中的某个参数加密要怎么设置呢

### ISSUE THREAD

**Issue by bingling123** [f0ng/autoDecoder#7]
加密的部分可以解密出来但是整个请求发送的时候就会出现解密错误

**Comment by bingling123** [comment]
![image](https://user-images.githubusercontent.com/48980951/201282034-f02ee764-d646-4f46-9a53-10a8b268ce5c.png)
类似这种的请求，明明我已经用了分隔符但仍然解密不成功

**Comment by f0ng** [comment]
可以参考下微信公众号文章 https://mp.weixin.qq.com/s/B-lBbVpJsPdCp1pjz2Rxdg

**Comment by f0ng** [comment]
看了下你的配置，你选中的是直接通过加解密算法的，再根据你在插件中的输入，这样使用是不行的，选中加解密算法只能直接加解密请求体，不支持json数据；支持json数据的话，需要自己写加解密接口
