### ISSUE TITLE
加解密问题

### ISSUE THREAD

**Issue by ketchup1995** [f0ng/autoDecoder#8]
![image](https://user-images.githubusercontent.com/87350553/218668811-52cc1ee8-c059-4f92-b2ce-ea14be1d018d.png)
如图，密文存在需要URL编码后才能解密，目前插件不存在该功能吗？
![image](https://user-images.githubusercontent.com/87350553/218669241-9d0f9bdb-06a0-4089-9d22-16d2a673bc92.png)

**Comment by ketchup1995** [comment]
补充：就是需要自动解码后再进行自动解密，否则返回包异常
![image](https://user-images.githubusercontent.com/87350553/218669427-07c78ac4-5b9a-4954-8c51-e77f01b55d67.png)

**Comment by f0ng** [comment]
插件暂不支持url解码后传入密文

**Comment by f0ng** [comment]
`0.21`版本优化该问题，改为进行URL解码后读取密文
